name: gpk_app
description: GPK — Gehandicapten Parkeerplaats. Vind gehandicaptenparkeerplaatsen in Nederland en de parkeerregels per gemeente.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^7.0.2          # OpenStreetMap-kaart
  latlong2: ^0.9.1            # coördinaten
  http: ^1.2.2               # Overpass / Nominatim
  url_launcher: ^6.3.0        # externe links (gpkwijs, route)

flutter:
  uses-material-design: true
